### ISSUE TITLE
how to retrive only one id 

### ISSUE THREAD

**Issue by fdciabdul** [alexmercerind/youtube-search-node#1]
i try with slice , but still showing too much id

**Comment by alexmercerind** [comment]
Hey there!
You get array of ids in the return.

Close the issue of following code works for you:

```javascript
(async () => {

    index = 0

    result = await searchYoutube("NoCopyrightSounds");
    console.log(result[index])
})();
```

Use index to get id at that index.
I have removed the video Labels for this release because youtube keeps changing stuff.
Consider starring the repo for updates.
